version: '3.8'
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    # stdin_open: true
    # tty: true